openapi: 3.0.3
info:
  description: You can use Admin API to create and manage your Human API users
  version: 1.0.0
  title: admin API
  termsOfService: https://www.humanapi.co/developer-terms
  contact:
    email: help@humanapi.co
    url: https://www.humanapi.co/contact
servers:
- url: https://admin.humanapi.co
  description: Production server
security:
- bearerAuth: []
tags:
- name: admin
  description: API endpoints to authorize a client app for the Admin API
paths:
  /v1/admin/token:
    post:
      tags:
      - admin
      description: Admin API client type token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tokenPayload'
      responses:
        '200':
          description: OK
components:
  schemas:
    tokenPayload:
      type: object
      required:
      - client_id
      - client_secret
      - type
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        type:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-readme:
  explorer-enabled: true
  proxy-enabled: true
